/** @format */
import "./style.css";
import Header_main from "@/components/header_main/header_main";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="main_home bg_color">
      <Header_main />
      {children}
    </div>
  );
}
